### ISSUE TITLE
1.1.0 fatal error

### ISSUE THREAD

**Issue by stutteringp0et** [bluewallweb/plg_http2push#1]
Enabling the plugin kills my site - 

0 - syntax error, unexpected '?'

**Comment by stutteringp0et** [comment]
with all the ternaries - that's going to be tough to find....  Sorry my error doesn't include a line number.

**Comment by clayfreeman** [comment]
It seems as though you're not on a new enough PHP version. I forgot to add a PHP 7.1 version requirement to the plugin. If possible, I would recommend upgrading PHP.
