### ISSUE TITLE
 Warning: DOMDocument::loadHTML(): Unexpected end tag : a in Entity, line

### ISSUE THREAD

**Issue by KEZEO** [bluewallweb/plg_http2push#16]
Hello after updated joomla to 3.8.10, i have this error 
Warning: DOMDocument::loadHTML(): Unexpected end tag : a in Entity, line: 1046 in /home/XXXXXXXXXXXX/plugins/system/http2push/http2push.php on line 126
Thank you

**Comment by clayfreeman** [comment]
Please use our issue template when submitting bug reports.
